IoT Project/Controllers/GalileoController.cs
using System;
using System.IO.Ports;
using System.Web.Mvc;
using System.Text;
using System.Net.NetworkInformation;

namespace IoT_Project.Controllers
{
    public class GalileoController : Controller
    {
        public string pingGalileo(string ip)
        {
            // Base variables
            const int timeout = 120;
            var response = " No Response";

            // Create the ping class and set options
            var ping = new Ping();
            var options = new PingOptions {DontFragment = true};

            // Create a buffer of 32 bytes of data to be transmitted. 
            const string data = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
            var buffer = Encoding.ASCII.GetBytes(data);
            

            // Ping the ip and get the reply
            var reply = ping.Send(ip, timeout, buffer, options);

            if (reply != null && reply.Status == IPStatus.Success)
            {
                response = " Address: <b>" + reply.Address + "</b>";
                response += " Round Trip time: <b>" + reply.RoundtripTime + "</b>";
                response += " Time to live: <b>" + reply.Options.Ttl + "</b>";
                response += " Don't fragment: <b>" + reply.Options.DontFragment + "</b>";
                response += " Buffer size: <b>" + reply.Buffer.Length + "</b>";
            }

            return response;
        }

        public string galileoRequest(string COM)
        {
            string response = "No Response";

            var port = new SerialPort(COM, 9600, Parity.None, 8, StopBits.One)
            {
                ReadTimeout = 1000,
                WriteTimeout = 1000
            };

            try
            {
                port.Open();
            }
            catch (Exception)
            {
                return response;
            }

            port.Write("s");

            try
            {
                response = port.ReadLine();
                response += "<br>" + port.ReadLine();
                response += "<br>" + port.ReadLine();
            }
            catch (TimeoutException)
            { }

            port.Close();

            return response;
        }
    }
}

IoT Project/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IoT_Project.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SensorHub
            ()
        {
            return View();
        }
    }
}

IoT Project/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Hello</h1>
    <p class="lead">Welcome to the Intel Galileo Internet of Things Project homepage!</p>
    <!--<p><a class="btn btn-primary btn-lg">Sample Button &raquo;</a></p>-->
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Sensor Hub Project</h2>
        <p>
            The sensor hub project allows remote viewing of sensor data over the web.
        </p>
        <p><a href="@Url.Action("SensorHub", "Home")" class="btn btn-default">View Project &raquo;</a></p>
    </div>
    <!--<div class="col-md-4">
        <h2>Example Project 2</h2>
        <p>This text would describe the second project.</p>
        <p><a class="btn btn-default">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Example Project 3</h2>
        <p>A description of the third project would go here.</p>
        <p><a class="btn btn-default">Learn more &raquo;</a></p>
    </div>-->
</div>

IoT Project/Views/Home/SensorHub.cshtml
@{
    ViewBag.Title = "Sensor Hub Project";
}

<script type="text/javascript" src="@Url.Content("~/Scripts/Views/SensorHub.js")"></script>

<h2>@ViewBag.Title</h2>

<p>Galileo IP: <input id ="galileoIP" type="text" value="192.168.0.106" /> COM Port: <input id="comPort" type="text" value="COM3" /></p>
<p class="info">Press ping to verify that the Galileo is on and connected to the network. <br /> Press start to begin recieving data. Data will update every five seconds. Press stop to stop recieving data. </p>
<p><a class="btn btn-default ping">Ping Galileo</a> <a class="btn btn-default start" style="margin-left:10px">Start</a> <a class="btn btn-default stop" style="margin-left:10px; display:none">Stop</a></p>
<p id="response"></p>

<div id="urls-container" style="display:none">
    @Html.Hidden("ping-url", Url.Action("pingGalileo", "Galileo", null))
    @Html.Hidden("galileo-request-url", Url.Action("galileoRequest", "Galileo", null))
</div>

IoT Project/Views/Home/WirelessSensors.cshtml
@{
    ViewBag.Title = "Wireless Sensors Project";
}

<script type="text/javascript" src="@Url.Content("~/Scripts/Views/WirelessSensors.js")"></script>

<h2>@ViewBag.Title</h2>

<p>Galileo IP: <input id ="galileoIP" type="text" value="192.168.0.106" /></p>
<p><a class="btn btn-default ping">Ping Galileo</a></p>
<p id="pingResponse"></p>

<p>COM Port: <input id="comPort" type="text" value="COM1" /> </p>
<p><a class="btn btn-default request">Request Data</a></p>
<p id="requestResponse"></p>

<div id="urls-container" style="display:none">
    @Html.Hidden("ping-url", Url.Action("pingGalileo", "Galileo", null))
    @Html.Hidden("galileo-request-url", Url.Action("galileoRequest", "Galileo", null))
</div>

IoT Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Galileo IoT</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Galileo IoT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sensor Hub Project", "SensorHub", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FGCU Software Engineering</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>